// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";
import { useButtonClick } from "@/hooks/useButtonClick";

export default function ContactSection(): React.JSX.Element {
  const handleButtonClick = useButtonClick();
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Ready to Start?"
          text="Let’s transform your garden today. Get in touch for a free, professional consultation."
          primaryButton={{
            text: "Book Free Quote",
            href: "https://www.google.co.uk",
            onClick: (e: React.MouseEvent) => {
              handleButtonClick(e);
            }
          } as any}
          secondaryButton={{
            text: "Call  01484 605 016",
            href: "tel:01484000000",
          }}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}