// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTwoColumn from '@/components/sections/faq/FaqTwoColumn';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqTwoColumn
          tag="Common Queries"
          title="Everything You Need to Know"
          description="Answers to frequently asked questions about our landscaping process."
          items={[
            {
              question: "What areas do you serve?",
              answer: "We primarily serve Huddersfield, Holmfirth, and the wider Yorkshire region.",
            },
            {
              question: "Do you offer free consultations?",
              answer: "Yes, we provide free site visits and no-obligation quotes for all potential projects.",
            },
            {
              question: "How long does a landscaping project take?",
              answer: "Timelines vary based on complexity, but we always provide a clear schedule during consultation.",
            },
            {
              question: "Are you fully insured?",
              answer: "Yes, we are fully insured for all landscaping work we undertake, giving you total peace of mind.",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
