// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroBillboardCarousel from '@/components/sections/hero/HeroBillboardCarousel';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroBillboardCarousel
          tag="Yorkshire's Premium Landscapers"
          title="Building Exceptional Outdoor Living Spaces in Huddersfield & Yorkshire"
          description="We blend professional landscaping expertise with local heart. From bespoke patio design to complete garden renovations, we turn your outdoor vision into a premium reality."
          primaryButton={{
            text: "Request A Free Quote",
            href: "#contact",
          }}
          secondaryButton={{
            text: "View Our Portfolio",
            href: "#portfolio",
          }}
          items={[
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3Fv83KUYlJoI2yCApMcJ43LguDH/uploaded-1782953985958-pkzybhtg.webp",
            },
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3Fv83KUYlJoI2yCApMcJ43LguDH/uploaded-1782953985957-z9tzks6p.webp?_wi=1",
            },
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3Fv83KUYlJoI2yCApMcJ43LguDH/uploaded-1782953985958-r3jgrgtk.webp",
            },
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3Fv83KUYlJoI2yCApMcJ43LguDH/uploaded-1782955666569-3kl2mknn.jpg?_wi=1",
            },
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3Fv83KUYlJoI2yCApMcJ43LguDH/uploaded-1782953985957-0e6lsyqa.webp?_wi=1",
            },
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3Fv83KUYlJoI2yCApMcJ43LguDH/uploaded-1782953985954-zkzga7my.webp?_wi=1",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
