// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroBillboardCarousel from '@/components/sections/hero/HeroBillboardCarousel';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroBillboardCarousel
          tag="Yorkshire's Premium Landscapers"
          title="Building Exceptional Outdoor Living Spaces in Huddersfield & Yorkshire"
          description="We blend professional landscaping expertise with local heart. From bespoke patio design to complete garden renovations, we turn your outdoor vision into a premium reality."
          primaryButton={{
            text: "Request A Free Quote",
            href: "#contact",
          }}
          secondaryButton={{
            text: "View Our Portfolio",
            href: "#portfolio",
          }}
          items={[
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3Fv83KUYlJoI2yCApMcJ43LguDH/uploaded-1782953985958-pkzybhtg.webp",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/street-texture-retro-tuscany-city_1203-5049.jpg",
            },
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3Fv83KUYlJoI2yCApMcJ43LguDH/uploaded-1782953985958-r3jgrgtk.webp",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/cityscape-office-buildings_1127-2949.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/view-futuristic-looking-city_23-2150946699.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/full-length-portrait-stylish-smiling-woman-walking-exotic-street-near-hotel-sunny-hot-day-spending-her-vacation-los-angeles_273443-2714.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
