// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsIconCards from '@/components/sections/metrics/MetricsIconCards';
import { Award, CheckCircle, ThumbsUp } from "lucide-react";
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsIconCards
          tag="Proven Reliability"
          title="Why Clients Trust Us"
          description="Over a decade of transforming local outdoor spaces with passion."
          metrics={[
            {
              icon: Award,
              title: "Years Experience",
              value: "15+",
            },
            {
              icon: CheckCircle,
              title: "Projects Completed",
              value: "500+",
            },
            {
              icon: ThumbsUp,
              title: "Happy Clients",
              value: "480+",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
