// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "portfolio" section.

import React from 'react';
import FeaturesImageBento from '@/components/sections/features/FeaturesImageBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function PortfolioSection(): React.JSX.Element {
  return (
    <div id="portfolio" data-section="portfolio">
        <SectionErrorBoundary name="portfolio">
              <FeaturesImageBento
          tag="Our Work"
          title="Showcasing Excellence Across Yorkshire"
          description="Explore our recent landscaping transformations throughout the region."
          items={[
            {
              title: "Huddersfield Patio",
              description: "Natural stone patio design.",
              imageSrc: "http://img.b2bpic.net/free-photo/city-view_1417-1895.jpg",
            },
            {
              title: "Holmfirth Garden",
              description: "Full garden renovation.",
              imageSrc: "http://img.b2bpic.net/free-photo/wooden-seats-by-pool-with-parasols_53876-146253.jpg",
            },
            {
              title: "Premium Paving",
              description: "Bespoke driveway solutions.",
              imageSrc: "https://storage.googleapis.com/webild/users/user_3Fv83KUYlJoI2yCApMcJ43LguDH/uploaded-1782953985957-z9tzks6p.webp",
            },
            {
              title: "Modern Terrace",
              description: "Contemporary living space.",
              imageSrc: "http://img.b2bpic.net/free-photo/covered-lifestyle-garden-with-indoor-outdoor-living_1127-3426.jpg",
            },
            {
              title: "Planting Design",
              description: "Curated residential garden.",
              imageSrc: "http://img.b2bpic.net/free-photo/beautiful-shot-houses-pamplona-spain-with-scenery-sunset-background_181624-24642.jpg",
            },
            {
              title: "Garden Path",
              description: "Detailed stonework finish.",
              imageSrc: "http://img.b2bpic.net/free-photo/analog-city-landscape-with-buildings-daylight_23-2149661429.jpg",
            },
            {
              title: "Outdoor Kitchen",
              description: "Bespoke patio feature.",
              imageSrc: "http://img.b2bpic.net/free-photo/fumigation_23-2148013411.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
