// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "portfolio" section.

import React from 'react';
import FeaturesImageBento from '@/components/sections/features/FeaturesImageBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function PortfolioSection(): React.JSX.Element {
  return (
    <div id="portfolio" data-section="portfolio">
        <SectionErrorBoundary name="portfolio">
              <FeaturesImageBento
          tag="Our Work"
          title="Showcasing Excellence Across Yorkshire"
          description="Explore our recent landscaping transformations throughout the region."
          items={[
            {
              title: "Huddersfield Patio",
              description: "Natural stone patio design.",
              imageSrc: "https://storage.googleapis.com/webild/users/user_3Fv83KUYlJoI2yCApMcJ43LguDH/uploaded-1782955171786-2nce6d9z.jpg?_wi=1",
            },
            {
              title: "Holmfirth Garden",
              description: "Full garden renovation.",
              imageSrc: "https://storage.googleapis.com/webild/users/user_3Fv83KUYlJoI2yCApMcJ43LguDH/uploaded-1782953985957-0e6lsyqa.webp?_wi=2",
            },
            {
              title: "Premium Paving",
              description: "Bespoke driveway solutions.",
              imageSrc: "https://storage.googleapis.com/webild/users/user_3Fv83KUYlJoI2yCApMcJ43LguDH/uploaded-1782953985957-z9tzks6p.webp?_wi=2",
            },
            {
              title: "Modern Terrace",
              description: "Contemporary living space.",
              imageSrc: "https://storage.googleapis.com/webild/users/user_3Fv83KUYlJoI2yCApMcJ43LguDH/uploaded-1782953985954-zkzga7my.webp?_wi=2",
            },
            {
              title: "Planting Design",
              description: "Curated residential garden.",
              imageSrc: "https://storage.googleapis.com/webild/users/user_3Fv83KUYlJoI2yCApMcJ43LguDH/uploaded-1782955666569-3kl2mknn.jpg?_wi=2",
            },
            {
              title: "Garden Path",
              description: "Detailed stonework finish.",
              imageSrc: "https://storage.googleapis.com/webild/users/user_3Fv83KUYlJoI2yCApMcJ43LguDH/uploaded-1782955676482-ujpw1039.jpg",
            },
            {
              title: "Pergolas ",
              description: "Pergolas and Convenience  ",
              imageSrc: "https://storage.googleapis.com/webild/users/user_3Fv83KUYlJoI2yCApMcJ43LguDH/uploaded-1782953985957-6evzosyn.webp",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
