// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import FeaturesBentoGrid from '@/components/sections/features/FeaturesBentoGrid';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
        <SectionErrorBoundary name="services">
              <FeaturesBentoGrid
          tag="Expert Landscaping Services"
          title="Comprehensive Garden Solutions"
          description="Tailored landscaping services designed to elevate your home's exterior appeal and functionality."
          features={[
            {
              title: "Bespoke Paving & Stone",
              description: "Expertly crafted patios and paths in natural stone.",
              imageSrc: "http://img.b2bpic.net/free-photo/photo-stone-texture-pattern_58702-14140.jpg",
            },
            {
              title: "Modern Fencing & Decking",
              description: "High-quality privacy solutions and stunning decking areas.",
              imageSrc: "http://img.b2bpic.net/free-photo/modern-wooden-fence-lush-green-hedge-garden-landscape_626616-510.jpg",
            },
            {
              title: "Professional Planting",
              description: "Expert landscape design with curated plants.",
              imageSrc: "http://img.b2bpic.net/free-photo/gardening_23-2148013398.jpg",
            },
            {
              title: "Water Features",
              description: "Add tranquility with custom-built ponds and water features.",
              imageSrc: "http://img.b2bpic.net/free-photo/chairs-white-garden-resort-chair_1203-4439.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
