/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import TextAnimation from "@/components/ui/TextAnimation";
import ScrollReveal from "@/components/ui/ScrollReveal";
import Button from "@/components/ui/Button";
import CheckList from "@/components/ui/CheckList";
import { cls } from "@/lib/utils";

const serviceCategories = [
  {
    title: "Landscaping & Garden Design",
    items: ["Complete garden transformations", "Garden design", "Soft landscaping", "Hard landscaping", "Landscape gardening"]
  },
  {
    title: "Patios & Paving",
    items: ["Porcelain patios", "Indian sandstone patios", "Natural stone paving", "Block paving", "Garden pathways", "Flagging"]
  },
  {
    title: "Driveways",
    items: ["Block paving driveways", "Tarmac driveways", "Gravel driveways"]
  },
  {
    title: "Decking",
    items: ["Timber decking", "Composite decking", "Verandas"]
  },
  {
    title: "Fencing",
    items: ["Timber fencing", "Decorative fencing", "Trellis", "Garden gates"]
  },
  {
    title: "Outdoor Structures",
    items: ["Pergolas", "Pagodas", "Gazebos", "Summer houses", "Garden sheds", "Timber outbuildings"]
  },
  {
    title: "Garden Features",
    items: ["Raised beds", "Rockeries", "Garden walling", "Dry stone walls", "Garden ponds", "Water features", "Fitted timber garden furniture", "Children's play areas"]
  },
  {
    title: "Lawns & Groundworks",
    items: ["Turfing", "Artificial grass (AstroTurf)", "Ground levelling", "Drainage", "Concreting", "Hardcore preparation"]
  }
];

const ServicesInline = () => {
  const colSpans = ["md:col-span-5", "md:col-span-7", "md:col-span-7", "md:col-span-5"];

  return (
    <section aria-label="Features section" className="py-20">
      <div className="flex flex-col gap-8 md:gap-10">
        <div className="flex flex-col items-center gap-2 w-content-width mx-auto">
          <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
            <p>{"Expert Landscaping Services"}</p>
          </div>

          <TextAnimation
            text={"Comprehensive Garden Solutions"}
            variant={"slide-up"}
            gradientText={true}
            tag="h2"
            className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
          />

          <TextAnimation
            text={"Tailored landscaping services designed to elevate your home's exterior appeal and functionality."}
            variant={"slide-up"}
            gradientText={false}
            tag="p"
            className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance"
          />

          {(undefined || undefined) && (
            <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
              {undefined && <Button text={undefined.text} href={undefined.href} variant="primary" />}
              {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary" animationDelay={0.1} />}
            </div>
          )}
        </div>

        <ScrollReveal variant="fade" className="w-content-width mx-auto">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-5">
            {serviceCategories.map((category, index) => (
              <div key={category.title} className="flex flex-col gap-3 xl:gap-3.5 2xl:gap-4 p-4 xl:p-5 2xl:p-6 card rounded border border-foreground/5">
                <h3 className="text-xl font-semibold leading-snug text-balance">{category.title}</h3>
                <CheckList items={category.items} className="text-sm text-accent" />
              </div>
            ))}
          </div>
        </ScrollReveal>
      </div>
    </section>
  );
};

export default function ServicesSection() {
  return (
    <div data-webild-section="services" id="services">
      <ServicesInline />
    </div>
  );
}
