// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import FeaturesBentoGrid from '@/components/sections/features/FeaturesBentoGrid';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
        <SectionErrorBoundary name="services">
              <FeaturesBentoGrid
          tag="Expert Landscaping Services"
          title="Comprehensive Garden Solutions"
          description="Tailored landscaping services designed to elevate your home's exterior appeal and functionality."
          features={[
            {
              title: "Paving & Stonework",
              description: "Expertly crafted patios, paths, and driveways using premium natural stone and porcelain.",
              imageSrc: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80",
            },
            {
              title: "Fencing & Decking",
              description: "High-quality timber and composite decking, alongside durable fencing solutions for privacy.",
              imageSrc: "https://images.unsplash.com/photo-1525088553748-01d6e24380cd?auto=format&fit=crop&q=80",
            },
            {
              title: "Landscape Design",
              description: "Comprehensive garden design services, from initial concept to full 3D visualization.",
              imageSrc: "https://images.unsplash.com/photo-1558904541-efa843a96f09?auto=format&fit=crop&q=80",
            },
            {
              title: "Planting Schemes",
              description: "Bespoke planting plans tailored to your garden's soil, aspect, and your personal style.",
              imageSrc: "https://images.unsplash.com/photo-1558905051-14e274af7819?auto=format&fit=crop&q=80",
            },
            {
              title: "Turfing & Lawns",
              description: "Professional installation of premium natural turf and high-quality artificial grass.",
              imageSrc: "https://images.unsplash.com/photo-1592424001807-26c715a818f1?auto=format&fit=crop&q=80",
            },
            {
              title: "Water Features",
              description: "Custom-built ponds, fountains, and contemporary water features to add tranquility to your space.",
              imageSrc: "https://images.unsplash.com/photo-1542361345-89e58247f2d5?auto=format&fit=crop&q=80",
            }
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
