// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialMarqueeOverlayCards from '@/components/sections/testimonial/TestimonialMarqueeOverlayCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialMarqueeOverlayCards
          tag="Kind Words"
          title="Hear From Our Happy Clients"
          description="See why homeowners across Huddersfield choose us for their landscaping needs."
          testimonials={[
            {
              name: "Simon ",
              role: "Client",
              company: "Huddersfield",
              rating: 5,
              quote: "I just wanted to thank Steven and his team for the work that has been carried out for us. We are totally delighted! From start to finish we were thoroughly impressed on how professional and punctual the team was. I will certainly be recommending your services to others.",
            },
            {
              name: "Kit White",
              role: "Client",
              company: "Huddersfield",
              rating: 5,
              quote: "We were thrilled with Steve’s work! We had some raised beds built and an Indian sandstone patio laid, the work was done...",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
