// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialMarqueeOverlayCards from '@/components/sections/testimonial/TestimonialMarqueeOverlayCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialMarqueeOverlayCards
          tag="Kind Words"
          title="Hear From Our Happy Clients"
          description="See why homeowners across Huddersfield choose us for their landscaping needs."
          testimonials={[
            {
              name: "Sarah Miller",
              role: "Homeowner",
              company: "Huddersfield",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/front-view-smiley-woman-looking-camera_23-2148317302.jpg",
            },
            {
              name: "James & Emma",
              role: "Clients",
              company: "Holmfirth",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/medium-shot-couple-decorating-home_23-2150633269.jpg",
            },
            {
              name: "David Thompson",
              role: "Property Owner",
              company: "Yorkshire",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/blue-eyed-bearded-male-using-laptop-cafe-street_613910-12216.jpg",
            },
            {
              name: "Linda Wright",
              role: "Client",
              company: "Huddersfield",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/friends-taking-care-their-plants-greenhouse_23-2149037274.jpg",
            },
            {
              name: "Mark Roberts",
              role: "Homeowner",
              company: "Holmfirth",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/outdoors-street-portrait-beautiful-young-brunette-woman_1153-5232.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
